### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by adipatijukir** [Nishant-Pathak/MathView#1]
I can not download your library , please fix your link library

**Comment by Nishant-Pathak** [comment]
Looking into it.

**Comment by adipatijukir** [comment]
Library Not yet added in to your project
Please look my ss
![screenshot_2017-03-14-12-51-27](https://cloud.githubusercontent.com/assets/20211539/23887566/505abab2-08b5-11e7-93c7-5d9cdcbc29bf.png)

or please check your link library , it is not found .
https://bintray.com/nishantpathak/public/MathView/0.6/link

Please sir , i very like your project.

**Comment by Nishant-Pathak** [comment]
Fixed in [PR](https://github.com/Nishant-Pathak/MathView/pull/2). See the updated README.md for usage.

-
Thanks
