### ISSUE TITLE
how to change textsize of formula

### ISSUE THREAD

**Issue by iShriyansh** [Nishant-Pathak/MathView#10]
hey bro, your mathview is working very good but i am not able to chnage its font size... i somehow able to changed its color white  "$$\\\\color{white}{"+tex+"}$$"  through this code but i am not able to change its font size please help.. and also strings need total 4 back slashs

**Comment by Nishant-Pathak** [comment]
Closing the issue due to inactivity. Please reopen if you still face the issue.
