### ISSUE TITLE
Failed to resolve dependency in M1 MacBook Pro 

### ISSUE THREAD

**Issue by ynjadhav** [Nishant-Pathak/MathView#16]
Hi Nishant,
Thanks for this awesome library.

I have used this in one of my project found it very useful. Earlier I was using MacBook Pro(intel chip) its wasn't giving any issue but on new MacBook Pro(M1) dependency is failed resolve. The same dependency version is working fine for Windows/Macbook with intel chips.

PFA for error I'm getting while running app.

<img width="894" alt="Screenshot 2022-10-11 at 5 35 48 PM" src="https://user-images.githubusercontent.com/47637655/195085064-9c658f25-7763-4d71-9b93-8aa519e23012.png">

**Comment by Nishant-Pathak** [comment]
Have you configured the repository?  
also you can switch to v1.2 . Please look details here https://jitpack.io/#Nishant-Pathak/MathView/v1.2

**Comment by ynjadhav** [comment]
Hi Nishant,
Thanks for replying.

Yes I have configured the repository. 

After I switch to v1.2 then **import com.nishant.math.MathView;**  giving me error.
