### ISSUE TITLE
Not able to render MathML

### ISSUE THREAD

**Issue by acircuit** [Nishant-Pathak/MathView#3]
We have a requirement of rendering all of our questions. The questions may be in ASCII Math or MathML.
We are able to render ASCII Math but it fails to render MathML and displays mathml as it is. Is there something we can do about this?

**Comment by Ezcred** [comment]
Can you share the error logs.

**Comment by Nishant-Pathak** [comment]
Can you share the error logs.

**Comment by Nishant-Pathak** [comment]
Closing it. Please reopen with logs.
