### ISSUE TITLE
Can latex be used for native display

### ISSUE THREAD

**Issue by tianshaokai** [Nishant-Pathak/MathView#6]

**Comment by Nishant-Pathak** [comment]
Yes, you can read more at https://www.mathjax.org/

**Comment by tianshaokai** [comment]
Thanks. This library must be displayed by WebView. I want to use textview to display it.

**Comment by tianshaokai** [comment]
If weview is used in a large number of pages, the memory will increase a lot.

**Comment by Nishant-Pathak** [comment]
Agree. There is a scope of optimisation. I will be happy if you want to contribute and solve the problem.
